import '../../public/css/style.css'

import { Inter } from 'next/font/google'
import { AuthUserProvider } from '../context/AuthUserContext'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="css/style.css" />
      </head>
        <body className={inter.className}>
          <AuthUserProvider>
            {children}
          </AuthUserProvider>
        </body>
        <Script rel='preload' type='module' src='js/index.js' crossOrigin='anonymous'/>
    </html>
  )
}